name: Workflow 语法检查

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 actionlint
        uses: devops-actions/actionlint@v1
