name: Workflow Syntax Check

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run actionlint
        uses: devops-actions/actionlint@v1
